## Get DC Museums from Yelp

In [52]:
# Imports dependencies
import requests
import json
import pandas as pd

In [53]:
# Set up the API call web location
url = 'https://api.yelp.com/v3/businesses/search'

In [54]:
# Register to use the Yelp API and get an API Key AND
#Import API key using config
from config import api_key

In [55]:
# Search parameters 
params = {
    'term': 'museum',
    'location': 'DC',
    'limit': 20
}

# Authorization headers
# repalce yelp api key 
headers = {
    'Authorization': 'Bearer {api_key}'
}

In [56]:
# Perform API request
data = requests.get(url, params=params, headers=headers)

In [57]:
# Grab data from the response
parsed = json.loads(data.text)

In [58]:
print(json.dumps(parsed, indent=4))

{
    "error": {
        "code": "VALIDATION_ERROR",
        "description": "'Bearer {api_key}' does not match '^(?i)Bearer [A-Za-z0-9\\\\-\\\\_]{128}$'",
        "field": "Authorization",
        "instance": "Bearer {api_key}"
    }
}

In [47]:
businesses = parsed["businesses"]
 
for business in businesses:
    print("Name:", business["name"])
    print("Rating:", business["rating"])
    print("Address:", " ".join(business["location"]["display_address"]))
    print("Phone:", business["phone"])
    print("\n")

Name: Smithsonian National Museum of Natural History
Rating: 4.5
Address: 1000 Constitution Ave NW Washington, DC 20004
Phone: +12026331000


Name: Newseum
Rating: 4.5
Address: 555 Pennsylvania Ave NW Washington, DC 20001
Phone: +18886397386


Name: Smithsonian National Air and Space Museum
Rating: 4.0
Address: Independence Ave And 6th St SW Washington, DC 20560
Phone: +12026331000


Name: National Gallery of Art
Rating: 4.5
Address: 6th St & Constitution Ave NW Washington, DC 20001
Phone: +12027374215


Name: National Portrait Gallery
Rating: 4.5
Address: 8TH St And F St NW Washington, DC 20001
Phone: +12026338300


Name: National Museum of American History
Rating: 4.0
Address: 14TH St And Constitution Ave NW Washington, DC 20002
Phone: +12026331000


Name: National Museum of African American History and Culture
Rating: 4.5
Address: 1400 Constitution Ave NW Washington, DC 20560
Phone: +18447503012


Name: United States Holocaust Memorial Museum
Rating: 4.5
Address: 100 Raoul Wallenberg Pl SW Washington, DC 20024
Phone: +12024880400


Name: United States Botanic Garden
Rating: 4.5
Address: 100 Maryland Ave SW Washington, DC 20001
Phone: +12022258333


Name: Smithsonian American Art Museum Renwick Gallery
Rating: 4.5
Address: 800 G St NW Washington, DC 20006
Phone: +12023571300


Name: International Spy Museum
Rating: 3.5
Address: 700 L'Enfant Plz Washington, DC 20024
Phone: +12023937798


Name: Hirshhorn Museum & Sculpture Garden
Rating: 4.0
Address: 7th St & Independence Ave Sw Washington, DC 20560
Phone: +12026331000


Name: Museum of the Bible
Rating: 4.5
Address: 400 4th St SW Washington, DC 20024
Phone: +18664306682


Name: National Geographic Museum
Rating: 3.5
Address: 1145 17th St NW Washington, DC 20036
Phone: +12028577700


Name: Ford's Theatre
Rating: 4.5
Address: 511 10th St NW Washington, DC 20004
Phone: +12023474833


Name: National Archives and Records Administration
Rating: 4.5
Address: 700 Pennsylvania Ave NW Washington, DC 20408
Phone: +18662726272


Name: The Kreeger Museum
Rating: 4.5
Address: 2401 Foxhall Rd NW Washington, DC 20007
Phone: +12023373050


Name: National Postal Museum
Rating: 4.5
Address: 2 Massachusetts Ave NE Washington, DC 20002
Phone: +12026335555


Name: Library of Congress
Rating: 4.5
Address: 101 Independence Ave SE Washington, DC 20540
Phone: +12027075000


Name: The Phillips Collection
Rating: 4.0
Address: 1600 21st St NW Washington, DC 20009
Phone: +12023872151

In [48]:
# create empty lists for museum data
museum_names = []
museum_ratings = []
museum_review_counts = []

# loop through each museum data, grab relevent info, and append it to empty lists 
for business in businesses:
    names = business['name']
    museum_names.append(names)
    ratings = business['rating']
    museum_ratings.append(ratings)
    counts = business['review_count']
    museum_review_counts.append(counts)

In [49]:
# create museum df
museum_df = pd.DataFrame(
    {'museum names': museum_names,
     'museum ratings': museum_ratings, 
     'number of museum reviews': museum_review_counts
    })

In [50]:
#Set index to count museums and add identifier
museum_df = museum_df.reset_index(drop=True)
museum_df

,museum names,museum ratings,number of museum reviews
0,Smithsonian National Museum of Natural History,4.5,1002
1,Newseum,4.5,920
2,Smithsonian National Air and Space Museum,4.0,1066
3,National Gallery of Art,4.5,653
4,National Portrait Gallery,4.5,553
5,National Museum of American History,4.0,629
6,National Museum of African American History an...,4.5,763
7,United States Holocaust Memorial Museum,4.5,755
8,United States Botanic Garden,4.5,456
9,Smithsonian American Art Museum Renwick Gallery,4.5,409
10,International Spy Museum,3.5,923
11,Hirshhorn Museum & Sculpture Garden,4.0,409
12,Museum of the Bible,4.5,219
13,National Geographic Museum,3.5,240
14,Ford's Theatre,4.5,426
15,National Archives and Records Administration,4.5,360
16,The Kreeger Museum,4.5,48
17,National Postal Museum,4.5,160
18,Library of Congress,4.5,450
19,The Phillips Collection,4.0,211

In [51]:
#Add column of museums names without spaces, for instagram hashtag
#Reset index to keep original index
museum_df['museum names no space'] = museum_df['museum names'].str.replace(" ","")
museum_df.reset_index(inplace=True, drop=True)

In [52]:
#Rearrange columns 
museum_df = museum_df[['museum names', 'museum names no space', 'museum ratings', 'number of museum reviews']]
museum_df

,museum names,museum names no space,museum ratings,number of museum reviews
0,Smithsonian National Museum of Natural History,SmithsonianNationalMuseumofNaturalHistory,4.5,1002
1,Newseum,Newseum,4.5,920
2,Smithsonian National Air and Space Museum,SmithsonianNationalAirandSpaceMuseum,4.0,1066
3,National Gallery of Art,NationalGalleryofArt,4.5,653
4,National Portrait Gallery,NationalPortraitGallery,4.5,553
5,National Museum of American History,NationalMuseumofAmericanHistory,4.0,629
6,National Museum of African American History an...,NationalMuseumofAfricanAmericanHistoryandCulture,4.5,763
7,United States Holocaust Memorial Museum,UnitedStatesHolocaustMemorialMuseum,4.5,755
8,United States Botanic Garden,UnitedStatesBotanicGarden,4.5,456
9,Smithsonian American Art Museum Renwick Gallery,SmithsonianAmericanArtMuseumRenwickGallery,4.5,409
10,International Spy Museum,InternationalSpyMuseum,3.5,923
11,Hirshhorn Museum & Sculpture Garden,HirshhornMuseum&SculptureGarden,4.0,409
12,Museum of the Bible,MuseumoftheBible,4.5,219
13,National Geographic Museum,NationalGeographicMuseum,3.5,240
14,Ford's Theatre,Ford'sTheatre,4.5,426
15,National Archives and Records Administration,NationalArchivesandRecordsAdministration,4.5,360
16,The Kreeger Museum,TheKreegerMuseum,4.5,48
17,National Postal Museum,NationalPostalMuseum,4.5,160
18,Library of Congress,LibraryofCongress,4.5,450
19,The Phillips Collection,ThePhillipsCollection,4.0,211

In [53]:
museum_df.to_csv(r'yelp_museums.csv')